# Generated by Django 2.1.2 on 2018-10-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='approve_job',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
