# Generated by Django 2.1.2 on 2018-10-13 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_inquiry_approve_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='inquiry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Inquiry'),
        ),
    ]
