# Generated by Django 2.1.2 on 2018-10-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20181013_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='inq_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
