# Generated by Django 2.1.2 on 2018-10-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20181013_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='inq_number',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
    ]
