# Generated by Django 2.1.2 on 2018-10-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20181013_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='inq_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
