# Generated by Django 2.1.2 on 2018-10-13 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20181013_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='inquiry',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Inquiry'),
        ),
    ]
