language: python
python:
  - "3.6.2"

services:
  - postgresql



install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c "create database users;" -U postgres
#   - cd dag_backend/
  - python manage.py makemigrations customer
  - python manage.py migrate

script:
  - coverage run --source=customer dag_backend/manage.py test

after_success:
  - coveralls
