# Generated by Django 2.1.2 on 2019-01-06 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('H', 'Hygiene'), ('T', 'Technical')], default='Hygiene', max_length=20)),
                ('inspection_date', models.DateField(null=True)),
                ('extra_details', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('inq_number', models.CharField(editable=False, max_length=20, null=True)),
                ('approve_job', models.BooleanField(default=False, null=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='inquiry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Inquiry'),
        ),
    ]
