# Generated by Django 2.1.2 on 2019-01-06 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest_type', models.CharField(choices=[('1', 'Mosquitoes'), ('2', 'Cockroaches'), ('3', 'Bats'), ('4', 'Rodents'), ('5', 'Bed bugs'), ('6', 'Termites'), ('7', 'Snakes'), ('8', 'Lizards'), ('9', 'Fleas'), ('10', 'Others')], max_length=12, null=True)),
                ('others_specify', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('PR', 'Public Residential'), ('PC', 'Public Commercial'), ('FP', 'Food Preparation'), ('WH', 'Warehouse/ Store'), ('PvR', 'Private Residential'), ('O', 'Others/ Specify')], default='Public Residential', max_length=12)),
                ('services_required', models.CharField(choices=[('C', 'Cleaning'), ('G', 'Gardening'), ('PC', 'Pest Control')], default='Cleaning', max_length=12)),
                ('number_of_floors', models.IntegerField(null=True)),
                ('estimated_area', models.IntegerField(null=True)),
                ('number_of_occupants', models.IntegerField(null=True)),
                ('description_of_terrain', models.TextField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('recodered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surfaces', models.CharField(choices=[('1', 'Ceramic'), ('2', 'Porcelain'), ('3', 'Granite'), ('4', 'Grass'), ('5', 'Marble'), ('6', 'Terazzo'), ('7', 'Wood'), ('8', 'Trees'), ('9', 'Carpet'), ('10', 'PVC/ Vinly'), ('11', 'Rubber'), ('12', 'Flower Bed'), ('13', 'Paint'), ('14', 'Steel'), ('15', 'Cement'), ('16', 'Hedge')], max_length=12, null=True)),
                ('surface_area', models.IntegerField(null=True)),
                ('others', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='surface',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspection.Surface'),
        ),
    ]
